In [3]:
import numpy as np

In [4]:
A = np.array([[3,7],[5,2]])

In [5]:
np.linalg.svd(A)

(array([[-0.85065081, -0.52573111],
        [-0.52573111,  0.85065081]]),
 array([8.71337969, 3.32821489]),
 array([[-0.59455781, -0.80405286],
        [ 0.80405286, -0.59455781]]))

In [6]:
B = np.array([[0,1,3], [2,3,1], [0,1,0]])

In [7]:
np.linalg.svd(B)

(array([[-0.56667985,  0.82277903,  0.04368772],
        [-0.80674247, -0.54329657, -0.23236915],
        [-0.16745308, -0.16692366,  0.97164601]]),
 array([4.34019342, 2.41561763, 0.57228713]),
 array([[-0.37175416, -0.72677875, -0.5775738 ],
        [-0.44982001, -0.40322372,  0.79691442],
        [-0.81207192,  0.5560605 , -0.17701953]]))

In [8]:
C = np.array([[5,7,6], [4,2,1], [3,4,1], [3,3,4], [5,4,1]])

In [9]:
np.linalg.svd(C)

(array([[-0.7027403 , -0.46685359, -0.21410908, -0.49155031, -0.02719193],
        [-0.28359468,  0.43753177,  0.58006323, -0.23058944, -0.58180339],
        [-0.33147393,  0.28537754, -0.61435714,  0.49436281, -0.43226775],
        [-0.38088944, -0.37286696,  0.49010103,  0.67827186,  0.12506689],
        [-0.41325343,  0.60839426,  0.00708838, -0.02755894,  0.67695516]]),
 array([14.71294705,  3.686851  ,  1.71356906]),
 array([[-0.60160874, -0.65302683, -0.46002487],
        [ 0.59545726,  0.01724365, -0.80320191],
        [ 0.53244491, -0.75713844,  0.37847564]]))